name: logistic_management_staff
description: Logistic Management Staff App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ars_dialog: ^1.0.8
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  community_material_icon: ^5.9.55
  connectivity_plus: ^2.2.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  flash: ^2.0.3+2
  flutter_multi_formatter: ^2.5.1
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.0.1
  google_fonts: ^2.2.0
  google_maps_flutter: ^2.1.1
  material_color_generator: ^1.1.0
  permission_handler: ^8.3.0
  pretty_json: ^2.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.11
  sliding_up_panel: ^2.0.0+1
  timeline_tile: ^2.0.0
  validators: ^3.0.0
  url_launcher: ^6.0.17
  image_picker: ^0.8.4+4
  jiffy: ^5.0.0
  flutter_image_compress: ^1.1.0

  socket_io_client: ^1.0.2
#  go_router: ^2.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - images/