name: logistic_management_staff
description: Logistic Management Staff App

publish_to: 'none'

version: 1.0.4

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ars_dialog: ^1.0.8
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  community_material_icon: ^5.9.55
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  flash: ^2.0.3+2
  flutter_multi_formatter: ^2.5.7
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.2.1
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.6
  material_color_generator: ^1.1.0
  permission_handler: ^9.2.0
  pretty_json: ^2.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  timeline_tile: ^2.0.0
  validators: ^3.0.0
  url_launcher: ^6.1.2
  jiffy: ^5.0.0
  flutter_image_compress: ^1.1.0
  path_provider: ^2.0.10

  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3
  signature: ^5.0.1

  device_info_plus: ^3.2.3

  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1

  flutter_bluetooth_serial: ^0.4.0
  barcode_widget: ^2.0.2


#  socket_io_client: ^1.0.2
#  go_router: ^2.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2

#dependency_overrides:
#  platform: ^3.1.0

flutter_icons:
  # image_path: "images/launcher/icon.jpg"
  ios: true
  android: true
  image_path: "images/launcher/icon.png"
  image_path_android: "images/launcher/icon.png"
  image_path_ios: "images/launcher/icon.png"
  adaptive_icon_background: "#7c7c7c"
  adaptive_icon_foreground: "images/launcher/icon.png"


flutter:

  uses-material-design: true

  assets:
    - images/